language: elixir
sudo: false
notifications:
  email: false

elixir:
  - 1.8
  - 1.7

otp_release:
  - 21.1
  - 20.3
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 18.3
    - elixir: 1.7
      otp_release: 18.3
env:
  global:
    - MIX_ENV=test

notifications:
  email: false

sudo: false

script:
  - mix test
  - mix credo
