---

name: Publish to Hex.pm

on:
  push:
    paths:
      - 'VERSION'
    branches:
      - master
  workflow_dispatch: {}

jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{ secrets.HEXPM_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.12
      - run: mix deps.get
      - run: mix compile --docs
      - run: mix hex.publish --yes

